### ISSUE TITLE
peerCount 0 and blockNumber stucked

### ISSUE THREAD

**Issue by Marow** [rkanadev/go-dubaicoinrk#4]
#### System information

Gdbix version: current Version
OS & Version: ubuntu

I run gdbix and my blockNumber stucked.
peerCount says 0

But why? how can i fix it?

**Comment by Marow** [comment]
Its fixed.

On my Server was "Layer7" active. Firewall.
Now its deactivated and i get peers

**Comment by rkanadev** [comment]
You are on the wrong github repo for dbix. Please go the official repo to
get the latest updates.
Official repo: https://github.com/dbix-project/go-dubaicoin
