### ISSUE TITLE
Site shows Reward of 5 DBIX but i get 6 DBIX

### ISSUE THREAD

**Issue by Marow** [rkanadev/go-dubaicoinrk#5]
#### System information

Gdbix version: newest
OS & Version:  Ubuntu 16.04

Hi, i get a block with my pool, but this shows only 5 Reward on Dubaicoin-DBIX-Pool... but why?
I get 6 DBIX of Mining a block and not 5...

**Comment by rkanadev** [comment]
you need to edit the rewards number from the pool source code you are
using. And use the official repo of dbix. my repo is just for development
purpose only. Thanks!

**Comment by Marow** [comment]
Thanks, i mean found it in payouts/unlocker.go 

Changing 5000000000000 to 6000000000000
